In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
from shapely.geometry import LineString, Point
from shapely.ops import nearest_points
from tqdm import tqdm

In [68]:
print(gpd.__version__)

0.8.1

## data

In [3]:
# change path to relative path - only for publishing
current_directory = os.path.dirname(os.path.abspath(__file__))
os.chdir(current_directory)

fishnet_path = "./sampleData/AirPollutantSurface/"
fishnet_100m_4_16_7h = gpd.read_file(fishnet_path + 'fishnet_100m_4_16_07h.shp')
fishnet_100m_4_16_8h = gpd.read_file(fishnet_path + 'fishnet_100m_4_16_08h.shp')
fishnet_100m_4_16_9h = gpd.read_file(fishnet_path + 'fishnet_100m_4_16_09h.shp')

locPath = "./sampleData/bicy_rental_loc/"
bicy_rental_loc = gpd.read_file(locPath + 'bicy_rental_loc.shp')

routePath = "./sampleData/bicy_route/"
bicy_OD_4_16_7_9 = gpd.read_file(routePath + 'bicy_sim_7_09.shp', encoding='utf-8')

C:\Users\MoongiChoi\.conda\envs\geo_env\lib\site-packages\geopandas\array.py:166: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  return GeometryArray(vectorized.from_shapely(data), crs=crs)
C:\Users\MoongiChoi\.conda\envs\geo_env\lib\site-packages\geopandas\array.py:166: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  return GeometryArray(vectorized.from_shapely(data), crs=crs)

# 1. Preprocessing: spatiotemporal Surface data
## 1.1. merging surface data

In [4]:
def process_and_merge_dataframes(start_hour, end_hour, Pollutant_column, date):
    def process_dataframe(df, h):
        new_column_name = 'dust_' + str(h)
        df = df.rename(columns={Pollutant_column: new_column_name})
        return df
    
    data = None
    
    date_h = "_".join(date.split('_')[1:])
    date = date.replace('_', '-')
    # 날짜 형식을 datetime 객체로 변환
    date_obj = datetime.strptime(date, '%Y-%m-%d')
    date_ymd = date_obj.strftime('%Y-%m-%d')
    
    for h in range(start_hour, end_hour+1):
        # 전역 변수에서 해당 시간의 DataFrame 가져오기
        df = globals().get('fishnet_100m_' + date_h + '_' + str(h) + 'h')
        if df is not None:
            # DataFrame 처리
            processed_df = process_dataframe(df, h)
            # 첫 번째 시간대의 경우, data 변수에 할당
            if h == start_hour:
                data = processed_df
            # 그 외의 시간대의 경우, 기존 data DataFrame과 병합
            else:
                data = pd.merge(data, processed_df[['dust_' + str(h)]], left_index=True, right_index=True)
        else:
            print(f"DataFrame for hour {h} not found")
    
    #delete -9999
    data = data[data != -9999].dropna()
    
    #add date column
    data['date'] = date_ymd
    
    # 컬럼 재정렬
    first_columns = [col for col in data.columns if col.upper() in ['FID', 'TARGET_FID', 'ID']]
    dust_columns = [col for col in data.columns if col.startswith('dust_')]
    date_columns = ['date']
    last_columns = [col for col in ['geometry'] if col in data.columns]
    new_column_order = first_columns + dust_columns + date_columns + last_columns

    data = data[new_column_order]
    
    return data

## 1.2. Divide the air pollutant concentration surface data into x-minute intervals

In [18]:
# 컬럼 이름 수정

def minuteIntervals_surface(data_h, hourRange, minuteInterval):

    df = data_h.copy()
    
    for col in df.columns:
        if col.startswith('dust_'):
            num = int(col.split('_')[1])
            if num < 10:
                new_col = col.replace(f"dust_{num}", f"dust_0{num}") # dust_ 뒤에 오는 숫자가 10보다 작으면 0을 붙이기. 예로 dust_9이면 dust_09로.
                df.rename(columns={col: new_col}, inplace=True)

    
    # Now divide the surface by time interval
    n_timeBetHour = int(60/minuteInterval) # n_timeBetHour: hour 사이에 몇개 만들래? n-1 개(10분 -> n_timeBetHour = 6 -> 6-1 = 5개)
    # print(n_timeBetHour)
    for hour in range(hourRange[0], hourRange[1]):

        if hour < 9: 
            dust_preT_list = list(df['dust_0' + str(hour)]) #기준이 되는 이전 시간의 dust 값: 예로 9시 ~ 10시면 9시
            dust_postT_list = list(df['dust_0' + str(hour + 1)]) #기준이 되는 이후 시간의 dust 값: 예로 9시 ~ 10시면 10시

        elif hour == 9:
            dust_preT_list = list(df['dust_0' + str(hour)]) #기준이 되는 이전 시간의 dust 값: 예로 9시 ~ 10시면 9시
            dust_postT_list = list(df['dust_' + str(hour + 1)]) #기준이 되는 이후 시간의 dust 값: 예로 9시 ~ 10시면 10시            

        else:            
            dust_preT_list = list(df['dust_' + str(hour)]) #기준이 되는 이전 시간의 dust 값: 예로 9시 ~ 10시면 9시
            dust_postT_list = list(df['dust_' + str(hour + 1)]) #기준이 되는 이후 시간의 dust 값: 예로 9시 ~ 10시면 10시

        # Step 1: 두 리스트 (dust_preT_list, dust_postT_list)에서 각 매칭되는 값을 빼서 새로운 리스트 생성
        dust_deviation_list = [post - pre for pre, post in zip(dust_preT_list, dust_postT_list)]
    #     print(dust_deviation_list[0:5])

        # Step 2: newList에 minuteInterval/60을 곱함
        dust_deviation_list = [val * (minuteInterval / 60) for val in dust_deviation_list] # dust_deviation_list은 이제 minuteInterval 해당하는 편차가 됌.
        #print("dust_deviation_list:", dust_deviation_list[0:10])  


        for t, t_Interv in enumerate(range(1, n_timeBetHour)):   # 이제 각 interval time마다 overlay를 만들 것임.
            minute = t_Interv*minuteInterval # minute은 이제 사이의 분이 됌.
            #print(minute)
            dust_deviation_list_minute = [x * (t+1) for x in dust_deviation_list] #해당 분에 해당하는 편차 값 - 10분이면 9~10시 사이 편차값 * 10/60 * 1, 20분이면 편차값 * 10/60 * 2
            globals()['dust_' + str(hour) + "_" + str(minute)] = [x + y for x, y in zip(dust_preT_list, dust_deviation_list_minute)] #preTime의 dust + 편차 값 더하기

            # 생성된 list를 원본 데이터에 합치기 
            if hour < 10:
                if minute < 10:
                    df['dust_0' + str(hour) + "_0" + str(minute)] = globals()['dust_' + str(hour) + "_" + str(minute)]
                else:
                    df['dust_0' + str(hour) + "_" + str(minute)] = globals()['dust_' + str(hour) + "_" + str(minute)]
            else:
                if minute < 10:
                    df['dust_' + str(hour) + "_0" + str(minute)] = globals()['dust_' + str(hour) + "_" + str(minute)]
                else:
                    df['dust_' + str(hour) + "_" + str(minute)] = globals()['dust_' + str(hour) + "_" + str(minute)]



    # column 정렬
    first_columns = [col for col in df.columns if col.upper() in ['FID', 'TARGET_FID', 'ID']]
    dust_columns = sorted([col for col in df.columns if col.startswith('dust')])
    date_clumns = ['date']
    last_columns = [col for col in ['geometry'] if col in df.columns]
    new_column_order = first_columns + dust_columns + date_clumns + last_columns

    df = df[new_column_order]

    return df

# 2. Preprocessing: Overlay spatiotemporal Air pollutant surface and bicycle routes
## 2.1. convert bicycle OD to routes that composes of segment

In [44]:
def process_gdf(ODdata, OD_Oid, OTime, DTime, bicyLocPoints, Loc_id, minuteInterval): # minute을 넣으면 o -> d 방향으로 minute만큼 라인을 잘라 point를 생성함. point는 중간 지점이 됌.
    
    
    '''
    OD_id와 Loc_id = 일치하는 id: OD_Oid는 시작점 id. loc_id는 대여소 위치.
    OTime과 DTime은 Origin, Destin의 Time.
    
    '''
    gdf = ODdata.copy()
    new_rows = []
    for index, row in tqdm(gdf.iterrows(), total = len(ODdata)):
        # Find the starting point in bicyLocPoints that matches o_cd
        # bike point의 sta_id와 input data의 o_cd가 비슷한 곳-> 출발 지점. 이 지점을 기준으로 d 방향으로 라인을 잘라야 하기 때문.
        start_point = bicyLocPoints.loc[bicyLocPoints[Loc_id] == row[OD_Oid], 'geometry'].iloc[0] #
        
        # Find the nearest point on the line to the start point - 이 작업이 바로 origin point 위치를 찾아주는 것.
        nearest = nearest_points(row['geometry'], start_point)
        start_nearest = nearest[0]
        
        # Replace the start point of the line with the nearest point
        line = LineString([start_nearest, row['geometry'].coords[-1]])
        
        # 시간 자르기: o_time과 d_time은 minuteInterval 비율로 자른 라인에 따라 다시 설정됌.
        o_time = datetime.strptime(row[OTime], '%Y-%m-%d %H:%M:%S')
        d_time = datetime.strptime(row[DTime], '%Y-%m-%d %H:%M:%S')
        duration = (d_time - o_time).total_seconds() / 60.0 # in minutes

        line: LineString = row['geometry']
        num_segments = int(np.ceil(duration / minuteInterval))
        
        segment_durations = [minuteInterval for _ in range(num_segments - 1)]
        last_segment_duration = duration - sum(segment_durations)
        segment_durations.append(last_segment_duration)
        
        # 포인트 생성하기
        segment_points = []
        accumulated_ratio = 0
        for i, dur in enumerate(segment_durations):
            new_o_time = o_time + timedelta(minutes=sum(segment_durations[:i]))
            new_d_time = new_o_time + timedelta(minutes=dur)
            
            segment_ratio = dur / duration
            point = line.interpolate(accumulated_ratio + segment_ratio / 2, normalized=True)
            segment_points.append(point)
            
            accumulated_ratio += segment_ratio

            new_row = row.copy()
            new_row['o_time'] = new_o_time.strftime('%Y-%m-%d %H:%M:%S')
            new_row['d_time'] = new_d_time.strftime('%Y-%m-%d %H:%M:%S')
            new_row['dur_new'] = dur
            new_row['geometry'] = point  # 이 부분을 추가합니다.
            new_rows.append(new_row)
        
    # 새로운 컬럼 'dur_new'를 기존 컬럼 리스트에 추가
    new_columns = list(gdf.columns) + ['dur_new']
    new_gdf = gpd.GeoDataFrame(new_rows, columns=new_columns)

    # set same crs
    new_gdf.crs = ODdata.crs
    
    # reset index
    new_gdf.reset_index(drop = True, inplace = True)
    
    return new_gdf

## 2.2. Overlay spatiotemporal Air pollutant surface and bicycle routes

In [60]:
bicy_OD_5min.head()

,unique_id,pType,birth,sex,ref,o_time,o_cd,o_nm,d_time,d_cd,d_nm,distRe,durRe,distSim,durSim,o_hour,d_hour,geometry,dur_new
0,66,내국인,1996,M,SPB-52900,2023-04-16 08:13:02,3758,서울남부출입국관리소,2023-04-16 08:14:30,1151.0,마곡역1번출구,0.00,1,0.7956,3.826667,8,8,POINT (126.82263 37.56232),1.466667
1,502,내국인,1989,M,SPB-31196,2023-04-16 07:39:25,1173,강서구청사거리(SH타워),2023-04-16 07:41:13,5082.0,가양역 7번출구,486.93,1,0.4420,2.243333,7,7,POINT (126.85379 37.55856),1.800000
2,503,내국인,1999,F,SPB-57144,2023-04-16 08:37:38,1173,강서구청사거리(SH타워),2023-04-16 08:39:45,5082.0,가양역 7번출구,0.00,2,0.4420,2.243333,8,8,POINT (126.85379 37.55856),2.116667
3,712,내국인,1973,N,SPB-35485,2023-04-16 08:11:11,2744,강서세무서 앞,2023-04-16 08:14:45,2701.0,마곡나루역 5번출구 뒤편,625.27,3,1.0158,6.243333,8,8,POINT (126.82457 37.56340),3.566667
4,1012,내국인,1967,N,SPB-52932,2023-04-16 07:27:43,4537,서울남부지방검찰청 후문,2023-04-16 07:30:57,770.0,목동역5번출구 교통정보센터 앞,456.52,3,0.6770,2.978333,7,7,POINT (126.86537 37.52266),3.233333

In [61]:
def calculate_dust_exposure(ODdata, OTime, DTime, spatioTemporalSurface):
    # 좌표체계
    print('initialize crs...')
    ODdata = ODdata.to_crs(spatioTemporalSurface.crs)
    
    # OTime date 추출
    ODdata['date'] = ODdata[OTime].str.split(' ').str[0]  # 날짜
    ODdata['o_time_dt'] = pd.to_datetime(ODdata[OTime])
    ODdata['d_time_dt'] = pd.to_datetime(ODdata[DTime])

    print('spatial join...')
    # 공간적으로 겹치는지 확인
    joined_gdf = gpd.sjoin(ODdata, spatioTemporalSurface, op='within')

    # 날짜가 일치하는 행만 필터링
    joined_gdf = joined_gdf[joined_gdf['date_left'] == joined_gdf['date_right']]
    
#     display(joined_gdf)
#     display(joined_gdf)

    tqdm.pandas(desc="dust_exposure") 
    
    # 시간과 날짜가 일치하는지 확인
    def find_dust_con(row):
        # 중간 시간 계산
        o_time = row['o_time_dt']
        d_time = row['d_time_dt']
        mid_time = o_time + (d_time - o_time) / 2
        mid_hour = mid_time.hour
        mid_minute = mid_time.minute
        
        # 중간 시간에 가장 가까운 dust 컬럼 찾기
        if mid_minute == 0:
            closest_dust_col = f"dust_{mid_hour:02d}"
        else:
            closest_dust_col = f"dust_{mid_hour:02d}_{(mid_minute // 10) * 10:02d}"

                
        # "_00" 제거
        if closest_dust_col.endswith("_00"):
            closest_dust_col = closest_dust_col[:-3]
#             print("Modified:", closest_dust_col)

        # dust_con 값 찾기
        if closest_dust_col in row.index:
            return row[closest_dust_col]
        else:
            return None

    # dust_con 컬럼 생성
    joined_gdf['dust_con'] = joined_gdf.progress_apply(find_dust_con, axis=1)

    # 최종 노출량 계산
    joined_gdf['dust_exp'] = joined_gdf['dur_new'] * joined_gdf['dust_con'] * 60 ## 현재 1분 단위이기 때문에 이를 1초 단위로 바꿔줌.
    

    # 명시적으로 병합
    ODdata = ODdata.merge(joined_gdf[['dust_con', 'dust_exp']], left_index=True, right_index=True, how='left')
    
#     display(ODdata)

    # NaN 처리
#     ODdata['dust_con'].fillna(np.nan, inplace=True)
#     ODdata['dust_exp'].fillna(np.nan, inplace=True)
    


#     ODdata = ODdata[columns]
    
    return ODdata

## Run codes
### 1. Preprocessing: spatiotemporal Surface data
#### 1.1. merging surface data

In [13]:
data_h = process_and_merge_dataframes(start_hour = 7, end_hour = 9, Pollutant_column = 'RASTERVALU', date = '2023_4_16')

In [14]:
data_h.head()

,TARGET_FID,Id,dust_7,dust_8,dust_9,date,geometry
1278,1278,1279,34.0833,31.9747,35.7419,2023-04-16,"POLYGON ((14115155.496 4499650.874, 14115155.4..."
1279,1279,1280,34.0833,31.9649,35.7189,2023-04-16,"POLYGON ((14115255.496 4499650.874, 14115255.4..."
1280,1280,1281,34.0833,31.9550,35.6960,2023-04-16,"POLYGON ((14115355.496 4499650.874, 14115355.4..."
1281,1281,1282,34.0833,31.9451,35.6730,2023-04-16,"POLYGON ((14115455.496 4499650.874, 14115455.4..."
1282,1282,1283,34.0833,31.9351,35.6502,2023-04-16,"POLYGON ((14115555.496 4499650.874, 14115555.4..."

#### 1.2. Divide the air pollutant concentration surface data into x-minute intervals

In [19]:
dust_7_9_5min = minuteIntervals_surface(data_h, hourRange = [7,9], minuteInterval = 5)

In [20]:
dust_7_9_5min.head()

,TARGET_FID,Id,dust_07,dust_07_05,dust_07_10,dust_07_15,dust_07_20,dust_07_25,dust_07_30,dust_07_35,...,dust_08_25,dust_08_30,dust_08_35,dust_08_40,dust_08_45,dust_08_50,dust_08_55,dust_09,date,geometry
1278,1278,1279,34.0833,33.907583,33.731867,33.556150,33.380433,33.204717,33.02900,32.853283,...,33.544367,33.85830,34.172233,34.486167,34.800100,35.114033,35.427967,35.7419,2023-04-16,"POLYGON ((14115155.496 4499650.874, 14115155.4..."
1279,1279,1280,34.0833,33.906767,33.730233,33.553700,33.377167,33.200633,33.02410,32.847567,...,33.529067,33.84190,34.154733,34.467567,34.780400,35.093233,35.406067,35.7189,2023-04-16,"POLYGON ((14115255.496 4499650.874, 14115255.4..."
1280,1280,1281,34.0833,33.905942,33.728583,33.551225,33.373867,33.196508,33.01915,32.841792,...,33.513750,33.82550,34.137250,34.449000,34.760750,35.072500,35.384250,35.6960,2023-04-16,"POLYGON ((14115355.496 4499650.874, 14115355.4..."
1281,1281,1282,34.0833,33.905117,33.726933,33.548750,33.370567,33.192383,33.01420,32.836017,...,33.498392,33.80905,34.119708,34.430367,34.741025,35.051683,35.362342,35.6730,2023-04-16,"POLYGON ((14115455.496 4499650.874, 14115455.4..."
1282,1282,1283,34.0833,33.904283,33.725267,33.546250,33.367233,33.188217,33.00920,32.830183,...,33.483058,33.79265,34.102242,34.411833,34.721425,35.031017,35.340608,35.6502,2023-04-16,"POLYGON ((14115555.496 4499650.874, 14115555.4..."

### 2. Preprocessing: Overlay spatiotemporal Air pollutant surface and bicycle routes
#### 2.1. convert bicycle OD to routes that composes of segment

In [65]:
display(bicy_OD_4_16_7_9[bicy_OD_4_16_7_9['unique_id'] == 11140])
display(bicy_rental_loc.head())
'''
지울 컬럼: pType, 
o_time, d_time: origin, destination time
o_cd: origin location id
o_nm: origin location name
d_cd: destination location id
d_nm: destination location name
distRe: distance (m)
durRe: duration (minutes)
distSim: 시뮬레이션된 distance (무시)
durSim: 시뮬레이션된 duration (무시)
o_hour: bicycle타기 시작한 시간의 h
d_hour: bicycle반납한 시간의 h
'''

,unique_id,pType,birth,sex,ref,o_time,o_cd,o_nm,d_time,d_cd,d_nm,distRe,durRe,distSim,durSim,o_hour,d_hour,geometry
41,11140,내국인,1988,M,SPB-68013,2023-04-16 07:41:41,1452,겸재교 진입부,2023-04-16 07:55:01,1447.0,면목역 3번출구,1130.0,13,1.203,7.068333,7,7,"LINESTRING (127.07506 37.58563, 127.07666 37.5..."

,sta_id,sta_nm,gungu,address,long,lat,sta_est,lcd_op,qr_op,op_type,geometry
0,301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130 경복궁역 7번출구 앞,37.575794,126.971451,2015-10-07,20,20,QR,POINT (126.97145 37.57579)
1,302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130 경복궁역 4번출구 뒤,37.575947,126.974060,2015-10-07,12,12,QR,POINT (126.97406 37.57595)
2,303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189 세종로공원,37.571770,126.974663,2015-10-07,8,8,QR,POINT (126.97466 37.57177)
3,305,종로구청 옆,종로구,서울특별시 종로구 세종로 84-1,37.572559,126.978332,2015-01-07,16,16,QR,POINT (126.97833 37.57256)
4,307,서울역사박물관 앞,종로구,서울특별시 종로구 새문안로 55 서울역사박물관 앞,37.570000,126.971100,2015-10-07,11,11,QR,POINT (126.97110 37.57000)

'\n지울 컬럼: pType, \no_time, d_time: origin, destination time\no_cd: origin location id\no_nm: origin location name\nd_cd: destination location id\nd_nm: destination location name\ndistRe: distance (m)\ndurRe: duration (minutes)\ndistSim: 시뮬레이션된 distance (무시)\ndurSim: 시뮬레이션된 duration (무시)\no_hour: bicycle타기 시작한 시간의 h\nd_hour: bicycle반납한 시간의 h\n'

In [45]:
bicy_OD_5min = process_gdf(ODdata = bicy_OD_4_16_7_9, OD_Oid = 'o_cd', OTime = 'o_time', DTime = 'd_time',
                           bicyLocPoints = bicy_rental_loc, Loc_id = 'sta_id', minuteInterval = 5)

100%|██████████| 3128/3128 [00:10<00:00, 307.38it/s]
C:\Users\MoongiChoi\.conda\envs\geo_env\lib\site-packages\geopandas\array.py:166: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  return GeometryArray(vectorized.from_shapely(data), crs=crs)

In [54]:
display(bicy_OD_5min[bicy_OD_5min['unique_id'] == 11140])

'''
o_time, d_time: 새로 나눠짐
dur_new: duration between vertices (minute base. 1.5: 1min 30sec)
'''

,unique_id,pType,birth,sex,ref,o_time,o_cd,o_nm,d_time,d_cd,d_nm,distRe,durRe,distSim,durSim,o_hour,d_hour,geometry,dur_new
54,11140,내국인,1988,M,SPB-68013,2023-04-16 07:41:41,1452,겸재교 진입부,2023-04-16 07:46:41,1447.0,면목역 3번출구,1130.0,13,1.203,7.068333,7,7,POINT (127.07740 37.58611),5.000000
55,11140,내국인,1988,M,SPB-68013,2023-04-16 07:46:41,1452,겸재교 진입부,2023-04-16 07:51:41,1447.0,면목역 3번출구,1130.0,13,1.203,7.068333,7,7,POINT (127.08224 37.58718),5.000000
56,11140,내국인,1988,M,SPB-68013,2023-04-16 07:51:41,1452,겸재교 진입부,2023-04-16 07:55:01,1447.0,면목역 3번출구,1130.0,13,1.203,7.068333,7,7,POINT (127.08578 37.58862),3.333333

'\no_time, d_time이 새로 나눠졌음.\ndistRe\n\n'

#### 2.2. Overlay spatiotemporal Air pollutant surface and bicycle routes

In [62]:
# 함수 호출

# 여기서 만약 날짜를 여러개 한다면:
# dust_7_9_5min_combined = gpd.pd.concat([dust_4_16_7_9_5min, dust_4_17_7_9_5min, dust_4_18_7_9_5min])

exposure_5min_7_9_gdf = calculate_dust_exposure(ODdata = bicy_OD_5min, OTime = 'o_time', DTime = 'd_time', spatioTemporalSurface = dust_7_9_5min)

initialize crs...
spatial join...

C:\Users\MoongiChoi\.conda\envs\geo_env\lib\site-packages\geopandas\sindex.py:87: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (idx, item) in enumerate(geometry.iteritems())
dust_exposure: 100%|██████████| 8239/8239 [00:00<00:00, 18759.28it/s]

In [63]:
exposure_5min_7_9_gdf.head()

'''
dust_con: constant exposure amount of dust at each vertex
dust_exp: Total exposure amount of dust along route
'''

,unique_id,pType,birth,sex,ref,o_time,o_cd,o_nm,d_time,d_cd,...,durSim,o_hour,d_hour,geometry,dur_new,date,o_time_dt,d_time_dt,dust_con,dust_exp
0,66,내국인,1996,M,SPB-52900,2023-04-16 08:13:02,3758,서울남부출입국관리소,2023-04-16 08:14:30,1151.0,...,3.826667,8,8,POINT (14117830.946 4517779.133),1.466667,2023-04-16,2023-04-16 08:13:02,2023-04-16 08:14:30,33.965867,2988.996267
1,502,내국인,1989,M,SPB-31196,2023-04-16 07:39:25,1173,강서구청사거리(SH타워),2023-04-16 07:41:13,5082.0,...,2.243333,7,7,POINT (14121299.819 4517251.317),1.800000,2023-04-16,2023-04-16 07:39:25,2023-04-16 07:41:13,38.798100,4190.194800
2,503,내국인,1999,F,SPB-57144,2023-04-16 08:37:38,1173,강서구청사거리(SH타워),2023-04-16 08:39:45,5082.0,...,2.243333,8,8,POINT (14121299.819 4517251.317),2.116667,2023-04-16,2023-04-16 08:37:38,2023-04-16 08:39:45,33.766700,4288.370900
3,712,내국인,1973,N,SPB-35485,2023-04-16 08:11:11,2744,강서세무서 앞,2023-04-16 08:14:45,2701.0,...,6.243333,8,8,POINT (14118046.891 4517931.852),3.566667,2023-04-16,2023-04-16 08:11:11,2023-04-16 08:14:45,33.905017,7255.673567
4,1012,내국인,1967,N,SPB-52932,2023-04-16 07:27:43,4537,서울남부지방검찰청 후문,2023-04-16 07:30:57,770.0,...,2.978333,7,7,POINT (14122588.944 4512211.485),3.233333,2023-04-16,2023-04-16 07:27:43,2023-04-16 07:30:57,45.329100,8793.845400